### PR TITLE
https:/api.minepi.com/v2

### PR DESCRIPTION
**Pull request by Madhurmila44**
Want to change api key

### CODE REVIEW

**Comment by Madhurmila44** [comment]
Dear repositers,
         I want to change this file.
Please help me about

**Comment by Madhurmila44** [comment]
My dear developers  please approve this file

**Comment by Madhurmila44** [comment]
http://Validation-key.qi0vicnbmgszrttsmdquwikjikopoylj7njrbhjrocuiaq0uibuqijd9a566uk9/validation-key.txt

**Comment by Madhurmila44** [comment]
Please  aproov

**Comment by dannybutterfield1880** [comment]
What is the address to your website I don't think your have uploaded the validation-key.txt correctly. Also to change your API key go to develop.pi, choose your app and select generate API key

**Comment by dannybutterfield1880** [comment]
Why have you created the pull request with your API key? This is not necessary and is exposing your API key to everyone here

**Comment by Madhurmila44** [comment]
Sir ,am I able to cancel it?

**Comment by dannybutterfield1880** [comment]
Yes you can go to your pull requests and select the pi network one and there should be a button to cancel

**Review by steeletrig1 — APPROVED** [review]

**Pull request closed without merging**
