### PR TITLE
Add wallet_address to scopes

### PR DESCRIPTION
**Pull request by Raminbnz**
Added wallet_address to the available scopes, and made a number of formatting changes to make it more clear what scopes are needed for what methods.

### CODE REVIEW

**Comment by Raminbnz** [comment]
Raminbnz

**Comment by medjamac** [comment]
https://minepi.com/maxamejama

**Comment by wasi4440** [comment]
[](url)

**Comment by Ngocphan94** [comment]
> Raminbnz

**Comment by Ngocphan94** [comment]
https://github.com/pi-apps/pi-platform-docs/pull/310#issue-1559219316

**Review by Kekanidji9555 — COMMENTED** [review]
GBAZKI2TPFNF2QKJ6HG3YJ4VU4GUMEBEEBV6J476IGULB4OPFQVV7W2H

**Comment by SAADSHAHKAZMII** [comment]
GCIFSQKA5TSWPDRGLTSURN4J7IS6IR3RKWJKHU2O7VJ7RMKCLK4SMJNT

**Pull request closed without merging**
