### PR TITLE
Doc/authentication guide

### PR DESCRIPTION
**Pull request by ChibuikeVictor090**
Have you heard of pi a crypto currency system that will benefit you from being able to make accessible to crypto market, where crypto currency will be made the first generation mainstay currency exchange

### CODE REVIEW

**Comment by ChibuikeVictor090** [comment]
Sure with pi

**Comment by ouuo66** [comment]
evrey goood

**Comment by 0342192294** [comment]
Đăng ký kyc

**Comment by 0342192294** [comment]
Phạm Hoài Nam

**Review by Jiggnubs — COMMENTED** [review]
Get

**Pull request closed without merging**
